name: Build

on:
  push:
    branches: master

jobs:
  build:
    runs-on: macOS-latest

    steps:
      - name: Clone Data Branch
        uses: actions/checkout@master
        with:
          ref: api-data
          path: api-data
      - name: Checkout
        uses: actions/checkout@master
      - name: Run code
        run: swift run
      - name: Copy new data to API Repo Folder
        uses: jcblw/bash@master
        with:
          args: "cp -rf data/* ~/workdir/api-data/data/"          
      - name: Push to repo
        working-directory: ~/workdir/api-data
        run: |
          git config credential.helper 'cache --timeout=120'
          git config user.email "manasan93@gmail.com"
          git config user.name "Manuel Sánchez"
          git add data
          git commit --allow-empty -m "Updated Via CircleCI -- Automated"
          # Push quietly to prevent showing the token in log
          git push -q https://${EVANGELIUM_KEY}@github.com/manasv/Evangelium.git api-data

